// MN-27102021-Deprecated via US-0008401
// 31.12.2020 / Acmatac SEING: US-0007876 Deprecate not used component, Due to testclass code coverage
public class MediaPlanMainTriggerHandler {//implements ITrigger{
    // Map<String, List<Media_Plan__c>> requiredSyncRecs = new Map<String, List<Media_Plan__c>>();
    // List<Media_Plan__c> termUpdatedMP = new List<Media_Plan__c>();
    // public void bulkBefore()
    // {
    // }

    // public void bulkAfter()
    // {
    // }
    
    // public void beforeInsert(SObject so){
    // }
    
    // public void beforeUpdate(SObject oldSo, SObject so){
    // }
    
    // public void beforeDelete(SObject so){   

    // }
    
    // public void afterInsert(SObject so){

    // }
    
    // public void afterUpdate(SObject oldSo, SObject so){
    //     // Media_Plan__c newMP = (Media_Plan__c) so;
    //     // if( GW_sObject.isFieldChanged(so, oldSo, Util.NS +'IO_Paper__c') ){
    //     //     termUpdatedMP.add(newMP);
    //     // }
    	
    // }
    
    // public void afterDelete(SObject so){
    // }

    // public void andFinally(){
    //     // GW_MediaPlan.syncRec(termUpdatedMP);
    // }
 
 }